version: "3"
services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/html --email rockymajji007@gmail.com --agree-tos --no-eff-email --staging -d shitpost.tech  -d www.shitpost.tech 
  nginx:
    image: nginx:mainline-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - web-root:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - server
    networks:
      - app-network
  
  server:
    build: .
    container_name: shitpost_server 
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache
    networks:
      - app-network
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data 
    ports:
      - '4321:5432'
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379 
volumes:
  data:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
    driver_opts:
      type: none
      device: /home/lily/ShitPost/server
      o: bind
networks:
  app-network:
    driver: bridge  