version: "3"
services:
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - data:/var/lib/postgresql/data 
    ports:
      - '4321:5432'
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379
  server:
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - redis
      - db
    environment:
      DB_HOST: db
      REDIS_URL: redis://cache
volumes:
  data: